# Generated by Django 4.2.16 on 2024-10-26 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='interviewee',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='interviewee_availability',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='interviewer',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='interviewer_availability',
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
        migrations.DeleteModel(
            name='Interview',
        ),
    ]
