# Generated by Django 4.2.16 on 2024-10-26 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='status',
        ),
    ]
