# Generated by Django 5.1.1 on 2024-09-28 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='interviewee_availability',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='interviewee_availability', to='interviews.availability'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interview',
            name='interviewer_availability',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='interviewer_availability', to='interviews.availability'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='availability',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('not booked', 'Not Booked')], default='not booked', max_length=10),
        ),
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('matched', 'Matched'), ('current', 'Current'), ('completed', 'Completed')], default='matched', max_length=10),
        ),
    ]
