# Generated by Django 4.2.16 on 2024-10-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_remove_availability_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
